apache:
        image: php:apache
        volumes:
        - "/srv/php:/var/www/html"
        links:
        - mysql
        ports:
        - "80:80"
        privileged: true

mysql:
        image: mysql:latest
        volumes:
        - "/srv/sql:/var/lib/mysql"
        environment:
         MYSQL_ROOT_PASSWORD: passroot
        privileged: true

