version: '2'

services:
  php:
    image: nimmis/apache-php5
    container_name: apache
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - /srv/docker/apache:/var/www/html
    links:
      - db

  db:
    image: mysql/mysql-server:5.6
    container_name: mysql 
    environment:
     - MYSQL_ROOT_PASSWORD=hunter2
